### ISSUE TITLE
compilation fails with [...]/build/settings/ui_appearance.h:1:30: fatal error: klocalizedstring.h: No such file or directory

### ISSUE THREAD

**Issue by bruecke** [papylhomme/diskmonitor#12]
Building a fresh clone of diskmonitor (both master and v0.3.1) fails with _klocalizedstring.h_ not found although the appropriate devel-package is installed.
Below is the excerpt of the build log:

```
//snip
[ 19%] Building CXX object settings/CMakeFiles/libsettings.dir/configdialog.cpp.o
In file included from [...]/diskmonitor/settings/appearance.h:24:0,
                 from [...]/diskmonitor/settings/configdialog.cpp:26:
[...]/diskmonitor/build/settings/ui_appearance.h:1:30: fatal error: klocalizedstring.h: No such file or directory
 #include <klocalizedstring.h>
                          ^
compilation terminated.
settings/CMakeFiles/libsettings.dir/build.make:72: recipe for target 'settings/CMakeFiles/libsettings.dir/configdialog.cpp.o' failed
//snap
```

As I found out the **ui_smart.h** will fail with the same error.

System: Fedora core 21 with latest KF5 packages from _dvratil's Copr_ repository

**Comment by bruecke** [comment]
It turns out that the compiler is missing the needed include directory **/usr/include/KF5/KI18n** because `KF5::I18n` is not added correctly in _settings/CMakeLists.txt_ file.

The following patch solved the problem for me:

```
diff --git a/settings/CMakeLists.txt b/settings/CMakeLists.txt
index 1662b6d..d977c02 100644
--- a/settings/CMakeLists.txt
+++ b/settings/CMakeLists.txt
@@ -21,6 +21,7 @@ target_link_libraries( libsettings
   Qt5::Core
   KF5::ConfigWidgets
   KF5::IconThemes
+  KF5::I18n
 )

 install( FILES diskmonitor.kcfg  DESTINATION ${KCFG_INSTALL_DIR})
```

Is there any better way to attach this patch to this thread?!

**Comment by papylhomme** [comment]
Weird, I should have encoutered this problem long ago.. As for a possible explanation, KF5::I18n might have been pulled by KF5::ConfigWidgets in older KF5 version, but this behaviour changed lately (I'm currently running frameworks 5.11 on Arch and everything is compiling just fine as is).

Anyway, thanks for the report & the investigation, your patch looks fine to me, I'm applying it right now.

Regarding the patch submission process, it suite me this way for small fixes, the other alternative being creating a clone of the repository in order to submit a pull request ; slightly overkill in such case ;) 

Please let me know if the master is compiling fine now
